version: "2"

services:
  lein:
    build:
      context: .
      dockerfile: lein.dockerfile
    volumes:
      - ".:/usr/src/app"
      - "./.m2:/root/.m2"
      - "./.aws:/root/.aws:ro"
    entrypoint: ["lein"]
    working_dir: "/usr/src/app"
  proxy:
    build:
      context: .
      dockerfile: datomic-proxy.dockerfile
    command: --port 0.0.0.0:8182 calendar-defender
    ports:
      - "8182:8182"
    volumes:
      - "./.aws:/root/.aws:ro"
  aws:
    image: mesosphere/aws-cli
    volumes:
      - "./.aws:/root/.aws:ro"
