version: "2"

services:
  lein:
    build:
      context: .
      dockerfile: lein.dockerfile
    volumes:
      - ".:/usr/src/app"
      - "./.m2:/root/.m2"
      - "./.aws:/root/.aws:ro"
    command: ["calendar-defender"]
    working_dir: "/usr/src/app"
    environment:
      - 'DATOMIC_APP_INFO_MAP={:app-name "calendar-defender"}'
      - 'DATOMIC_ENV_MAP={:env :local}'
    ports:
      - "8182:8182"
  aws:
    image: mesosphere/aws-cli
    volumes:
      - "./.aws:/root/.aws:ro"
  tools-deps:
    build:
      context: .
      dockerfile: tools-deps.dockerfile
    volumes:
      - ".:/usr/src/app"
      - "./.m2:/root/.m2"
      - "./.aws:/root/.aws:ro"
    working_dir: "/usr/src/app"
