version: "2"

services:
  lein:
    build:
      context: .
      dockerfile: lein.dockerfile
    volumes:
      - ".:/usr/src/app"
      - "./.m2:/root/.m2"
      - "./.aws:/root/.aws:ro"
    entrypoint: ["lein"]
    working_dir: "/usr/src/app"
  aws:
    image: mesosphere/aws-cli
    volumes:
      - "./.aws:/root/.aws:ro"
